-- 메타데이터: DB 연결 저장소. PG(런타임)·H2 PostgreSQL 모드(테스트) 공용 문법만 사용.
-- CDC 등록 테이블 (마일스톤 4). PK 존재·supp.log ALL은 등록 시점에 검증 완료된 상태로 저장된다.
CREATE TABLE IF NOT EXISTS registered_tables (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_name          VARCHAR(128) NOT NULL,
    table_name           VARCHAR(128) NOT NULL,
    source_connection_id BIGINT       NOT NULL,
    target_connection_id BIGINT       NOT NULL,
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (schema_name, table_name)
);

CREATE TABLE IF NOT EXISTS db_connections (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL UNIQUE,
    db_type       VARCHAR(20)  NOT NULL DEFAULT 'ORACLE',
    role          VARCHAR(10)  NOT NULL,  -- SOURCE|TARGET (검증은 DbConnectionService — H2 테스트 호환 위해 DB CHECK 미사용)
    host          VARCHAR(255) NOT NULL,
    port          INT          NOT NULL,
    database_name VARCHAR(100) NOT NULL,
    username      VARCHAR(100) NOT NULL,
    password      VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
