-- 메타데이터: DB 연결 저장소. PG(런타임)·H2 PostgreSQL 모드(테스트) 공용 문법만 사용.
-- CDC 등록 테이블 (마일스톤 4). PK 존재·supp.log ALL은 등록 시점에 검증 완료된 상태로 저장된다.
CREATE TABLE IF NOT EXISTS registered_tables (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_name          VARCHAR(128) NOT NULL,
    table_name           VARCHAR(128) NOT NULL,
    source_connection_id BIGINT       NOT NULL,
    target_connection_id BIGINT       NOT NULL,
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (schema_name, table_name)
);

-- schema change topic에서 소비한 DDL 이벤트 (7절 승인 워크플로).
-- 토픽 retention(24h) 만료 전에 backend poller가 적재해두는 것이 원본 보존 수단이다.
CREATE TABLE IF NOT EXISTS ddl_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kafka_offset BIGINT       NOT NULL UNIQUE,
    event_ts_ms  BIGINT       NOT NULL,
    scn          VARCHAR(40),
    schema_name  VARCHAR(128),
    table_name   VARCHAR(128),
    ddl_text     VARCHAR(100000) NOT NULL,
    state        VARCHAR(16)  NOT NULL,  -- SNAPSHOT | DETECTED | APPROVED | REJECTED
    note         VARCHAR(1000),
    decided_at   TIMESTAMP
);

CREATE TABLE IF NOT EXISTS db_connections (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL UNIQUE,
    db_type       VARCHAR(20)  NOT NULL DEFAULT 'ORACLE',
    role          VARCHAR(10)  NOT NULL,  -- SOURCE|TARGET (검증은 DbConnectionService — H2 테스트 호환 위해 DB CHECK 미사용)
    host          VARCHAR(255) NOT NULL,
    port          INT          NOT NULL,
    database_name VARCHAR(100) NOT NULL,
    username      VARCHAR(100) NOT NULL,
    password      VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
